# Generated by Django 3.2.4 on 2021-07-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_post_post_comments_post_content_post_reactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_content',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.pseudo_user'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.post_comments'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.post_reactions'),
        ),
        migrations.AddField(
            model_name='post_comments',
            name='com_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.pseudo_user'),
        ),
        migrations.AddField(
            model_name='post_comments',
            name='comment_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post_reactions',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.pseudo_user'),
        ),
        migrations.AddField(
            model_name='post_reactions',
            name='like_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
