# Generated by Django 3.2.4 on 2021-07-30 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_auto_20210730_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post_comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 30, 18, 22, 45, 519397, tzinfo=utc), null=True),
        ),
    ]
