# Generated by Django 3.2.4 on 2021-07-30 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_auto_20210730_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudo_user',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
