# Generated by Django 3.2.4 on 2021-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_auto_20210730_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudo_user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
