# Generated by Django 3.2.4 on 2021-07-31 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0006_alter_pseudo_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comments',
            name='pub_date',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
