# Generated by Django 3.2.4 on 2021-07-31 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0008_auto_20210731_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comments',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='pub_hour',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 6, 45, 41, 925045, tzinfo=utc), null=True),
        ),
    ]
