# Generated by Django 3.2.4 on 2021-07-31 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0009_auto_20210731_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.AddField(
            model_name='post_reactions',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.post'),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='pub_hour',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 6, 47, 40, 77527, tzinfo=utc), null=True),
        ),
    ]
