# Generated by Django 3.2.4 on 2021-08-02 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0010_auto_20210731_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_comments',
            old_name='com_auth',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post_comments',
            old_name='comment_text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.pseudo_user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='pub_hour',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 38, 50, 448136, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Post_reactions',
        ),
    ]
