# Generated by Django 3.2.4 on 2021-08-02 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostApp', '0011_auto_20210802_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudo_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='pub_hour',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 18, 12, 13, 115211, tzinfo=utc), null=True),
        ),
    ]
