# Generated by Django 3.2.4 on 2021-08-05 15:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0019_auto_20210805_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
